spring:
  application:
    # 应用名称,
    # 注意:
    # 根据spring.cloud.config.discovery.service-id找到配置中心后,
    # 会根据此项目名称去配置中心找对应的配置文件: user-service.yml
    name: user-service

    # 消息总线配置
  #    bus:
  #      enabled: true
  #      trace:
  #        enabled: true
  #      refresh:
  #        enabled: true
  # kafka 配置消息总线使用
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    consumer:
#      # 消息分组编号
#      group-id: config-server

# 应用服务 WEB 访问端口
server:
  port: 8081

# actuator配置
#management:
#  endpoints:
#    # 开启actuator
#    enabled-by-default: true
#    web:
#      exposure:
#        # 开启: 提供refresh端点,可以使用接口主动刷新配置中心的配置文件内容
#        # 开启refresh刷新配置中心的配置信息, 开启hystrix监控面板
#        include: refresh,hystrix.stream

# feign使用熔断机制保护
#feign:
#  hystrix:
#    enabled: true


logging:
  level:
    org.springframework.cloud.sleuth: debug
