spring:
  application:
    # 应用名称
    name: spring-cloud-gateway-9093
  cloud:
    gateway:
      # 路由
      routes:
        # 断言
        - id: config_route
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
          uri: http://127.0.0.1:8082/getOrder

        # gateway配合注册中心实现负载均衡
        - id: lb_route
          predicates:
            - Path=/lb/**
          filters:
            - StripPrefix=1
          uri: lb://order-service

        # gateway配合注册中心实现负载均衡
        - id: user_service_loadbalancer_route
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
          uri: user://user-service


        # 基于redis实现 令牌桶限流
        - id: ratelimiter_router
          predicates:
            - Path=/ratelimiter/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                deny-empty-key: true
                keyResoler: '#{@ipAddressKeyResolver}'
                redis-rate-limiter.replenishRate: 1 # 令牌生成速度: 每秒钟生成1个
                redis-rate-limiter.burstCapacity: 2 # 令牌桶容量
          uri: lb://order-service

        # 校验请求信息 cookie
        - id: cookie_router
          predicates:
            - Path=/cookie/**
            - Cookie=name,mic # 要求请求信息的cookie必须有name,且name的值必须为mic
          filters:
            - StripPrefix=1
          uri: lb://order-service

        # 自定义断言,校验用户请求是否携带固定参数,根据其值校验登录权限
        - id: zsw_router
          predicates:
            - Path=/zswRoute/**
            - ZswAuth=sso_user_account # 要求请求信息的cookie必须有sso_user_account,再根据其值查询是否授权登录
          filters:
            - StripPrefix=1
          uri: lb://order-service

        # 自定义断言,校验用户请求是否携带固定参数,根据其值校验登录权限
        - id: user_service_router
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
          uri: user://user-service

      # gateway配合注册中心实现负载均衡,发现请求地址,从eureka注册中心定位
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  redis:
    host: 127.0.0.1
    port: 6379

  # sleuth链路追踪设置
  sleuth:
    sampler:
      probability: 1.0 # 采样比例: 1.0表示全部,默认0.1即10%
  # 启动的zipkin服务地址
#  zipkin:
#    base-uri: http://127.0.0.1:9411/


server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    #    org.springframework.cloud.sleuth: debug
    root: debug
