spring:
  application:
    # 应用名称
    name: spring-cloud-config-server-9091

  # spring cloud config
  cloud:
    config:
      server:
        # git 地址,用户名,密码
        git:
          uri: https://github.com/zhangshiwei1992/spring-cloud-config-file.git
          username: zhangshiwei1992
          password: ec35608321

    # 消息总线配置
  #    bus:
  #      enabled: true
  #      trace:
  #        enabled: true
  #      refresh:
  #        enabled: true
  # kafka 配置消息总线使用
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    consumer:
#      # 消息分组编号
#      group-id: config-server

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka



