server:
  port: 8083

spring:
  # 应用名称,
  # 注意:
  # 根据spring.cloud.config.discovery.service-id找到配置中心后,
  # 会根据此项目名称去配置中心找对应的配置文件: 如 goods-service-provider.yml
  application:
    name: goods-service-provider

  main:
    banner-mode: log
  profiles:
    active: main, ${DEPLOY_ENV}
  datasource:
    url: jdbc:mysql://rm-2ze3qg1crdkv9l4ts4o.mysql.rds.aliyuncs.com:3306/zulin-dev?autoReconnect=true&useUnienabledcode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: zulin
    password: Hexia8866
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
